#:schema node_modules/wrangler/config-schema.json
name = "code-launch"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[env.production]
route = { pattern = "*", zone_id = "" }

[build]
command = "npm run pages:build"
