name = "cody"
compatibility_date = "2024-09-23"
main = "build/server/index.js"

# Compatibility flags for Node.js modules
compatibility_flags = ["nodejs_compat"]

# Serve static assets from build/client
[site]
bucket = "./build/client"

# Rules for static asset handling
[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true
