import { createRequestHandler } from '@remix-run/cloudflare';

// @ts-ignore - This file is generated by the build process
import * as build from '../build/server';

const requestHandler = createRequestHandler({
  build,
  mode: process.env.NODE_ENV,
});

export default {
  async fetch(request: Request, env: any, ctx: any): Promise<Response> {
    try {
      return await requestHandler(request, {
        cloudflare: { env, ctx },
      });
    } catch (error) {
      console.error('Error handling request:', error);
      return new Response('Internal Server Error', { status: 500 });
    }
  },
};
