import { createRequestHandler } from '@remix-run/cloudflare';

export default {
  async fetch(request: Request, env: any, ctx: any): Promise<Response> {
    try {
      // @ts-ignore - This file is generated by the build process
      const build = await import('../build/server/index.js');

      const requestHandler = createRequestHandler({
        build,
        mode: 'production',
        getLoadContext: () => ({
          cloudflare: { env, ctx },
        }),
      });

      return await requestHandler(request);
    } catch (error) {
      console.error('Error handling request:', error);
      return new Response(`Internal Server Error: ${error.message}\n\nStack: ${error.stack}`, {
        status: 500,
        headers: { 'Content-Type': 'text/plain' }
      });
    }
  },
};
